channels:
- defaults
- http://ssb.stsci.edu/astroconda
dependencies:
- astroquery=0.3.10
- bokeh>=1.0,<1.4
- django=2.2.5
- flake8=3.7.8
- inflection=0.3.1
- ipython=7.9.0
- jinja2=2.10.3
- jsonschema=3.2.0
- matplotlib=3.1.0
- nodejs=10.13.0
- numpy=1.16.4
- numpydoc=0.9.2
- pandas=1.0.0
- pip=19.1.1
- postgresql=9.6.6
- psycopg2=2.7.5
- pysiaf==0.7.1
- python=3.6.4
- pytest=5.2.2
- pytest-cov=2.7.1
- scipy=1.3.0
- setuptools=41.0.1
- sphinx=2.4.0
- sqlalchemy=1.3.13
- twine=2.0.0
- pip:
  - asdf==2.5.2
  - astropy==4.0.1
  - authlib==0.14.1
  - codecov==2.0.15
  - jwedb>=0.0.3
  - pysqlite3==0.2.2
  - stsci_rtd_theme==0.0.2
  - git+https://github.com/spacetelescope/jwst@0.15.0
